export enum NODE_TYPE { ROOT = 'ROOT', DEPENDENCY = 'DEPENDENCY' }
export enum NODE_STATUS { VULNERABLE = 'VULNERABLE', CLEAN = 'CLEAN' }

export enum LINK_STATUS { VULNERABLE = 'VULNERABLE', CLEAN = 'CLEAN' }